### ISSUE TITLE
HTTPS 서버로 실행시 필요한 세팅

### ISSUE THREAD

**Issue by KimJuHyang** [kookmin-sw/2019-cap1-2019_3#14]
HTTP 에서는 카메라 사용이 제한되어 HTTPS 로 바꿔야하는 문제가 있었습니다.
이로인해 HTTPS 로 세팅하였구요, 각자 서버를 여실때의 명령어 방식이 변경되었습니다.

 **프로젝트 상단에 생긴 폴더, 인증서, setting.py 코드 부분 다시 pull 받으셔야합니다.** 

- 기존 
`python3 manage.py runserver 0.0.0.0:8000`

- 변경 
` python3 manage.py runsslserver 0.0.0.0:8000 `

되지않으신다면 python-runsslserver 를 install 해주셔야합니다.
그 밖의 오류가 있으시면 남겨주세요.

**Comment by 20163156** [comment]
python--runsslserver -> pip3 install django-sslserver
