### ISSUE TITLE
Step 1. start design

### ISSUE THREAD

**Issue by escs34** [kookmin-sw/2019-cap1-2019_3#2]
스토리 :
-(사용자) "나"는 영상에서 이미지를 한장씩 떼어 화명에 띄우는 프로그램을 만들고 싶다.
-표준 입력으로 영상의 path를 입력 하면, 콘솔에 입력해 감에 따라 1장씩 화면에 출력한다.
-1장씩 출력하는 것 만으로는 영상에서 처음의 매우 일부분 밖에는 볼 수 없다. 100장씩 뛰어넘고 출력하는 방법도 고안한다.

**Comment by escs34** [comment]
![step1_naive](https://user-images.githubusercontent.com/28584128/54661583-2d24cf80-4b1e-11e9-883e-cf0badddde85.png)

**Comment by escs34** [comment]
-class diagram 제작 도중,  몇가지 문제 사항이 예측 되었습니다.
-이에 대한 논의 사항을 다음 issue에서 완전히 해결한 후 이 issue로 복귀하겠습니다.
-그 때 까지 위 사항에 대한 질의는 comment로 남겨주시기 바랍니다.

**Comment by escs34** [comment]
Step1. Future change detected:

위 issue의 결과로  웹 서버 환경을 고려한 새 class diagram을 제작하였습니다.

![step1-2_ future change detected_layer_refactoring](https://user-images.githubusercontent.com/28584128/54817590-acf79900-4cda-11e9-8a58-f1d3f78069fe.png)

**Comment by escs34** [comment]
위와 같은 웹서버 환경을 고려한 class diagram의 제작후 문제가 생겼습니다.

초기에 영상이 제대로 열리는 지 확인하기 위해 만들었을 뿐인 showNext1,100,1000을 
수행하기 위해 거의 대부분의 클래스에서 getThisFrame등의 불필요한 함수를 만들어야
합니다. 이는 이후의 모든 서비스에서 필요하지 않은 기능이기에 클래스내에 꼭필요한
기능들만 남기고 삭제해야 합니다. 따라서 서비스를 재정의 합니다.

스토리 재정의:
(사용자) "나"는 서버에서 영상을 확인하는 프로그램을 만들 예정이다.
이 서비스는 두 가지 방식으로 제공되는데
1.영상의 주소를 보내면 서버에서 자체적으로 영상을 찾아 open한다.
2.영상을 열어서 1장씩 보내면 서버에서 받아서 처리한다.

제대로 동작하는지 확인 하기 위해 두 경우 모두 서버측에서
1번째, 100번째, 1000번째 frame을 열어서 눈으로 확인한다.

**Comment by escs34** [comment]
![step1-2_ future change detected_layer_refactoring](https://user-images.githubusercontent.com/28584128/54818161-fa283a80-4cdb-11e9-81b3-aaa3747c4100.png)


변경사항
-이전 class들이 가지고 있는 무의미한 함수들을 지우고 목적에 맞는 함수들만을 남겼습니다.

-class diagram에서 오 표기된 composition 화살표 방향 일부를 수정하였습니다.

-이미지에 대한 처리 과정이 선택한 서비스의 종류에 따라 다르기 때문에
 Commander가 아닌 Receiver에서ImgLoader를 사용합니다.
-Receiver는 클라이언트로부터 사진을 받을 시 commander로 넘겨 사진을 띄워주기만 하며,
 주소를 받을 시 ImgLoader를 사용해 영상을 열어서 넘겨줍니다.

(선택 사항. receiver에서 데이터를 받는 역할 + 서비스의 일부분을 동작해 주는 기능이
섞여있으므로, service activater class를 따로 만들 수도 있으나 이는 아직 보류합니다.)

**Comment by KimJuHyang** [comment]
> 1.영상의 주소를 보내면 서버에서 자체적으로 영상을 찾아 open한다.
> 2.영상을 열어서 1장씩 보내면 서버에서 받아서 처리한다.

2번의 기능을 하는것이 getThisFrame 이고, 이것이 1프레임당 1장씩 넘겨주는 함수라고 이해했습니다.
그럼 getThisFrame 함수의 내부는 영상에서 오로지 1장만 캡처해서 넘겨주는것인데, 
전체 프레임수가 만약 1400프레임이라고 치면 1400번 호출되어 1장씩 넘겨주는것인지 궁금합니다.

**Comment by escs34** [comment]
네. openCV 에서는 영상의 임의 접근방법을 제공하지 않습니다.  따라서 전체 영상을 다 보려면 1400번의 호출을 해야 합니다.

**Comment by KimJuHyang** [comment]
1장만 출력하는 함수를 따로 분리한다면.. 함수를 부를때마다 늘 1번째 프레임만 1400번 나오지않나요? 호출할때마다 인자값을 넘겨주지않는이상,  어떻게  프레임을 누적시켜서 다음 프레임을 출력해주는지 이해가 가지않습니다.

따로 몇번째 프레임을 출력해주어야할지 값을 가지지도 않고, 가진다 한들 임의접근을 제공하지않으니까 3번째 프레임을 출력해야겠다 라는 개념이 안통하므로 값을 가져도 무용지물이구요. 제가 맞게 이해한건가요?
