### ISSUE TITLE
YouTube 댓글 API 문제점

### ISSUE THREAD

**Issue by 20163156** [kookmin-sw/2019-cap1-2019_3#4]
<img width="1440" alt="스크린샷 2019-04-01 오후 4 04 12" src="https://user-images.githubusercontent.com/26539921/55310550-aa93fc80-549b-11e9-86d7-1753f169d76a.png">

기존 이용하려고 했던 youtube에서 제공하는 댓글 api를 사용해보니
최대 100개까지의 댓글만 가져올수 있는 문제가 발견되었습니다
어떻게 해결할까요? 아마도 youtube data api는 사용할 수 없을 것 같습니다.

**Comment by leejj5645** [comment]
api를 사용하는 대신에 직접 유튜브 웹사이트를 크롤링해서 전체 댓글을 가져오도록 해야할 것 같습니다.
크롤링 프로그램은 bs4와 selenium을 사용해 구현할 수 있을 것 같습니다.
