### ISSUE TITLE
lstm 모델 성능과 새로운 gboost 모델

### ISSUE THREAD

**Issue by leejj5645** [kookmin-sw/2019-cap1-2019_3#5]
처음에 사용하려 했던 lstm 모델의 성능이 저하하여 새로운 모델 gboost 를 사용하기로 했다.
gboost의 모델은 훈련데이터에 한해 75% 정확도를 보였다. 정확도를 더 높이기 위해 뉴스 헤드라인을 6가지 감정 anger, disgust, fear, joy, happiness, sadness, surprise으로 분류해놓은 데이터를 추가하기로 했다.

**Comment by leejj5645** [comment]
데이터 추가 한 결과 
추가 하기전에 분류하지 못하는 문장들에 대해서 분류할 수 있었다. 트위터 데이터가 감정 분류를 제대로 하지 못하는 것 같아 다른 데이터들을 섞어 여러번 학습시켜보기로 결정하였다.

**Comment by 20163156** [comment]
https://www.kaggle.com/eray1yildiz/emotion-classification/version/1
위의 데이터들을 추가해서 학습시키면 좋을 것 같습니다.
