### ISSUE TITLE
발표 및 계획서의 문제점 및 해결방안

### ISSUE THREAD

**Issue by KimJuHyang** [kookmin-sw/2019-cap1-2019_3#6]
피드백 받은 사항들을 어떻게 해결해야 할지 논의 해야할 것 같습니다.
크게 분류를 하자면,

**> 1. 추후 감성분석의 정확도를 어떻게 평가할것인지**

**> 2. 감성분석의 목표가 모호하다는 문제점**
` - 타겟층을 확실히 하여 감성분석의 목표를 확립하고자 한다면, 타겟층은 어떻게 할 지 논의`

**> 3. 비디오 모듈의 기능 추가 문제**
` - 사용자의 웹캠으로 시청자의 표정을 읽어와 감성분석 하는 기능을 추가할 것인지 문제`
 
그 외 논의 해야할 문제점과 해결방안이 있다면 작성해주세요.

**Comment by 20163156** [comment]
1. 댓글팀의 경우 학습데이터를 training set 과 test set으로 나눠서 측정한 성능을 지표로 사용하면 될 것 같습니다.
   또는 직접 레이블링한 댓글을 만들어 일치하는지 비교하는것도 가능합니다.

2.타겟층이 사용자와 크리에이터 둘다로 공통적으로 잡았는데에 비해 예상 UI는 사용자 중심으로 맞춰져서
   분석결과를 사용자가 보는 결과 따로 크리에이터가 보는 결과는 대시보드 처럼 2개의 UI를 만들 수 있습니다.

3.  프로젝트가 쉽다는 평가가 있으므로 웹캠까지 추가하는 것이 좋겠습니다.

**Comment by KimJuHyang** [comment]
그럼 예상 UI를 크리에이터 기준으로 하나 더 만들어봐야겠습니다. 감사합니다 ~
