### ISSUE TITLE
댓글 판별 정확성 향상을 위한 이슈

### ISSUE THREAD

**Issue by leejj5645** [kookmin-sw/2019-cap1-2019_3#8]
기존에 댓글 번역을 위해 번역 시 정확성이 더 높아 사용하려던  네이버 파파고 API가 일일 한도량이 매우 적어 댓글을 번역하기에 힘든다는 판단을 내렸다. 따라서 구글의 translation API 중 하나인 cloud translation API를 사용하여 한도 제한없이 사용이 가능하다.
번역 시 이모티콘이 있으면 안되기에 제외.
중요한 감정 데이터인 이모티콘에 대한 정보는 누실되는 것을 고려해야한다.

**Comment by 20163156** [comment]
이모티콘에 관해서는 이모티콘을 판별해 일일이 해당 단어를 대신 넣어주는 방법을 고려 하면 좋겠습니다.
예를 들어
sentence : 솔직해서 좋아요 👍 -> 솔직해서 좋아요 엄지척 
sentence : 가방 다 예쁘다 💛 -> 가방 다 예쁘다 사랑 
sentence : 너무예쁘세요 😍 -> 너무예쁘세요 사랑에 빠졌어요

이런식으로 이모티콘 대신 이모티콘에 해당하는 감정을 단어나 문장으로 매치해서 replace해주면 좋을 듯 합니다.

**Comment by 20163156** [comment]
위의 이모티콘에 해당하는 단어를 일일이 넣어주는 방법을 적용하였고
댓글 정확성을 향상 시키기 위해 네이버 맞춤법 검사기에 쿼리를 날려 맞춤법에 맞는 문장들이 예측 코드에 인풋으로 들어가게끔 수정하였습니다.
